# action.yml
name: 'Checkstyle'
description: 'Run Java Checkstyle'
branding:
  icon: 'code'  
  color: 'red'

inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'

  checkstyle_config:
    description: 'Checkstyle config file'
    required: true
    default: 'google_checks.xml'

  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'

# outputs:
#   time: # id of output
#     description: 'The time we greeted you'

runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
  #   - ${{ inputs.who-to-greet }}
