on: [push]

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: A job to run checkstyle
    steps:
    - name: Run checkstyle step
      # id: hello
      uses: kohougen/CheckStyle-Action@master
      # with:
      #   who-to-greet: 'Mona the Octocat'
    # # Use the output from the `hello` step
    # - name: Get the output time
    #   run: echo "The time was ${{ steps.hello.outputs.time }}"
